<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>f86b1a12-e930-4fae-b665-eca2d0f1e504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basicBootstrapForm']/div[7]/div/multi-select/div[2]/ul/li[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ng-scope.ui-elemfocus > a.ui-corner-all</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>221b0549-e829-40f2-ac5f-fa576ebb5331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-corner-all</value>
      <webElementGuid>2fb07ca6-db52-451c-a353-40fd29145524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>32a0a225-7ee0-44a8-b717-19f0d4130fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basicBootstrapForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-4 col-xs-4 col-sm-4&quot;]/multi-select[1]/div[2]/ul[@class=&quot;ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all&quot;]/li[@class=&quot;ng-scope ui-elemfocus&quot;]/a[@class=&quot;ui-corner-all&quot;]</value>
      <webElementGuid>ea423ce8-dd0c-4dd5-8041-c50549c9650e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[7]/div/multi-select/div[2]/ul/li[8]/a</value>
      <webElementGuid>d6c908e4-d6d6-480e-807a-d15d9ce6a6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>14bcc246-df7b-45b1-b794-eb3e17c74c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dutch'])[1]/following::a[1]</value>
      <webElementGuid>7f7e2322-2e6d-488a-823a-997896df6d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danish'])[1]/following::a[2]</value>
      <webElementGuid>cc0a34d8-198f-42be-9a0f-73d8fc8fc780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estonian'])[1]/preceding::a[1]</value>
      <webElementGuid>1f240169-a3c9-47de-83d7-443b13557839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filipino'])[1]/preceding::a[2]</value>
      <webElementGuid>b88a48b6-f9c6-4927-9fa1-b6cdf37daf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>6c198639-f0e7-4c5c-a219-2f7de134af66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//multi-select/div[2]/ul/li[8]/a</value>
      <webElementGuid>de99a76e-1c4a-48a2-8c11-ac8939bea526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>604ca5ba-d80a-44d4-a7b2-3e58c8bd3b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
