<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Languages_msdd</name>
   <tag></tag>
   <elementGuidId>fb169015-a0bd-4a92-94b7-e431a964d6f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3836aa1-891b-4a89-8c71-679eaca485ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-multiselect ui-state-default ui-widget</value>
      <webElementGuid>4de0498e-6719-4cb6-9f90-321f32a3c9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msdd</value>
      <webElementGuid>14e82802-f93a-4ca3-8a46-a0314d2a6e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msdd&quot;)</value>
      <webElementGuid>858fdea7-a051-450e-b15b-61f2436d1db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='msdd']</value>
      <webElementGuid>1a9b6d95-b579-404f-8d1e-74f329289caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[7]/div/multi-select/div</value>
      <webElementGuid>d5f25662-10f8-46c6-a3e3-57e62ff3fd12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages'])[1]/following::div[2]</value>
      <webElementGuid>39cf089f-23a6-43a9-81be-9301c1a195f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hockey'])[1]/following::div[3]</value>
      <webElementGuid>045aa6b4-3c9d-4c15-af6c-463c3f16308c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arabic'])[1]/preceding::div[1]</value>
      <webElementGuid>fc763bbb-4257-474b-8001-47ea2c8bd006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulgarian'])[1]/preceding::div[1]</value>
      <webElementGuid>464a43de-6bcd-49e5-b34b-a58c431abd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//multi-select/div</value>
      <webElementGuid>cf802c30-c04a-4629-8452-ccc2685ae9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'msdd']</value>
      <webElementGuid>201aa5ba-903e-4bcf-b8f3-07abfbe6114a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
