<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_secondpassword</name>
   <tag></tag>
   <elementGuidId>eafdf5ea-689c-4ac0-8de6-a5147be9b34d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondpassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#secondpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35fba425-4942-4a58-9439-ad741cb2b9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondpassword</value>
      <webElementGuid>0a2ae57e-e243-4dc8-9285-509620b404fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8104b2da-b278-4566-8e59-8f09b1d705c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>e3c87421-ac66-4751-9391-bd864790c795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>CPassword</value>
      <webElementGuid>8e207aa6-ecdc-4206-a15b-0e39ffff5b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validatepasswords(this)</value>
      <webElementGuid>549c8937-7cf1-4310-810f-cfff57d0a8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondpassword&quot;)</value>
      <webElementGuid>091e4589-2a36-4281-ad58-93c56d77baa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondpassword']</value>
      <webElementGuid>96e3a38f-1bb5-4d6f-a804-b3e15c22c82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[13]/div/input</value>
      <webElementGuid>83bdf37e-e764-40e7-8449-1cfb257d6c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>44040eed-8a78-4284-a8ab-60e272b21cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'secondpassword' and @type = 'password']</value>
      <webElementGuid>64d443b1-8015-4780-ba64-4db8e17a49a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
