<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month                               _920c21</name>
   <tag></tag>
   <elementGuidId>59c10ae7-d014-434c-bb22-1fd0e4b18b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@type='text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-control.ng-pristine.ng-untouched.ng-invalid.ng-invalid-required</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c69a19d-401a-4467-8d92-a619810a519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bc1e6ec-22c6-4450-81a8-97f3fe773d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>ae2badf9-260e-41d2-a78c-0c06a6197c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>2f243350-4f36-43cc-a488-eaffa71a4ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>monthbox</value>
      <webElementGuid>da899625-8353-49ff-93c4-a7d08a009553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>monthbox=''</value>
      <webElementGuid>3ccbdb4c-25a4-4647-a2ee-44a084ca9a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Month
                                January
                                February
                                March
                                April
                                May
                                June
                                July
                                August
                                September
                                October
                                November
                                December
                            </value>
      <webElementGuid>52fcc2bf-6f8e-4713-9676-70f431a2d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basicBootstrapForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-3 col-xs-3 col-sm-3&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>de7d0877-aac2-4387-adc8-5a47798604b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@type='text'])[4]</value>
      <webElementGuid>ca209d6e-c4dd-42e8-9388-a33e128ae324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[11]/div[2]/select</value>
      <webElementGuid>44a7a8e8-32ac-45a7-97f9-b8893bd17e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Birth'])[1]/following::select[2]</value>
      <webElementGuid>1deac45a-d6a4-43ec-803b-8c7de851508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[2]/following::select[2]</value>
      <webElementGuid>f540ce9b-f5dd-4f17-8d92-bccaea65c223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[2]</value>
      <webElementGuid>2699511a-2999-46d1-9b84-584e55081908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/preceding::select[2]</value>
      <webElementGuid>2d9278ab-43a4-461a-aa2e-4e9ed4481b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>01b755bc-f18c-4801-9c2e-6e9550266bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @placeholder = 'Month' and (text() = '
                                Month
                                January
                                February
                                March
                                April
                                May
                                June
                                July
                                August
                                September
                                October
                                November
                                December
                            ' or . = '
                                Month
                                January
                                February
                                March
                                April
                                May
                                June
                                July
                                August
                                September
                                October
                                November
                                December
                            ')]</value>
      <webElementGuid>b0e99a5a-cbeb-4986-a512-dea35a795a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
