<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address_form-control ng-untouched _b1abf7</name>
   <tag></tag>
   <elementGuidId>658b0c0e-d2bf-4b81-bf56-35cb80ba5eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basicBootstrapForm']/div[2]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.ng-untouched.ng-valid.ng-dirty.ng-valid-parse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>198f901c-9dce-4e1c-92e3-3d9f249b07d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8134ddf9-9f68-48a9-b52f-fa5faa3cf135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty ng-valid-parse</value>
      <webElementGuid>e1ce9c20-5df8-4455-b1e0-e783776f2cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>Adress</value>
      <webElementGuid>cc4b809b-6745-4b0c-8a14-5d46a5e97b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basicBootstrapForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-8 col-xs-8 col-sm-8&quot;]/textarea[@class=&quot;form-control ng-untouched ng-valid ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>4da5d375-88ad-4b61-9438-4cdcea73923b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[2]/div/textarea</value>
      <webElementGuid>c666c6e4-261a-4f34-a5c5-a0139c7e2eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::textarea[1]</value>
      <webElementGuid>c8390cd8-61b4-48b0-b35a-bc3e58305fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Name*'])[1]/following::textarea[1]</value>
      <webElementGuid>20d24e41-3cc3-4337-8c4c-b3a36d568e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4f8f0d6b-1499-4fd3-aecc-8b999ad77b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide a valid email id for further updates'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c4da4260-b534-4fda-b4ad-2cc03844bee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9dc4e2b0-07cf-44df-b2cb-0c814f52bd11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
