<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Skip Sign In_enterimg</name>
   <tag></tag>
   <elementGuidId>ac52b241-c92f-43aa-b5d7-d2cb03a99f6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='enterimg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#enterimg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c620d57b-54b8-4526-9fa7-012a1c71105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>enter.png</value>
      <webElementGuid>07766d38-c556-404a-a090-7a0792bf852f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>d761a71b-8ce4-46e9-b4b8-f6ccdb076840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enterimg</value>
      <webElementGuid>4d88342d-d92b-4bd9-9478-14b730b16443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enterimg&quot;)</value>
      <webElementGuid>773558e1-9023-4770-bf6e-c8199d955be8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='enterimg']</value>
      <webElementGuid>6227289e-bef2-4d4c-8acf-96acdc89d259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/span/a/img</value>
      <webElementGuid>1b05f2a5-add8-4deb-8551-4208d6d8022f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[2]</value>
      <webElementGuid>4c664ba7-9f21-425b-85b4-aca4a3bb2164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>f93e5522-0734-4e88-bfdb-d68961106619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'enter.png' and @alt = 'logo' and @id = 'enterimg']</value>
      <webElementGuid>2681083c-8f19-42aa-8a38-cb90846f6df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
